FROM mcr.microsoft.com/windows/servercore:ltsc2019

ADD ./envoy-static.exe ./envoy-static.exe

ENTRYPOINT ["envoy-static.exe", "-c", "./envoy-config/bootstrap.yaml", "--log-path", "./logs/envoy.log"]